name: Build and Deploy PH Barangay Web to Linode
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_CNC_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CNC_TOKEN }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_PROD }}
      - name: Docker Build and Push, Kubernetes apply
        run: |
          docker build --tag ${{ secrets.DOCKERHUB_CNC_USERNAME }}/${{ secrets.DOCKERHUB_PROD_REPOSITORY }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_CNC_USERNAME }}/${{ secrets.DOCKERHUB_PROD_REPOSITORY }}:${{ github.sha }}
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
          sed -i'' -e 's/DOCKERHUB_USERNAME/${{ secrets.DOCKERHUB_CNC_USERNAME }}/g' -e 's/DOCKERHUB_REPOSITORY/${{ secrets.DOCKERHUB_PROD_REPOSITORY }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' -e "s/DOCKER_CONFIG/$DOCKER_CONFIG/g" k8s_prod.yml
          kubectl apply -f k8s_prod.yml
